//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RFMapTool.rc
//
#define IDOK2                           3
#define IDOK3                           4
#define IDD_ABOUTBOX                    100
#define IDD_RFMAPTOOL_FORM              101
#define IDD_BACK_BORDER                 101
#define ID_FILE_COLLISION_OPEN          101
#define IDD_FORM_BORDER                 101
#define ID_FILE_COLLISION_SAVE          102
#define ID_FILE_ENTITY_OPEN             103
#define ID_FILE_MAP_ENTITY_OPEN         103
#define IDD_DIALOGBAR                   103
#define ID_FILE_ENTITY_SAVE             104
#define ID_FILE_MAP_ENTITY_SAVE         104
#define IDR_MAINFRAME                   128
#define IDR_RFMAPTTYPE                  129
#define IDD_DIALOG_RENDER               130
#define IDD_TAB_COLLISION               137
#define IDD_TAB_ENTITY                  138
#define IDD_TAB_BORDER                  139
#define IDD_TAB_PARTICLE                146
#define IDD_TOOL_BASE                   148
#define IDD_DIALOG1                     150
#define IDD_COLL_FILE                   151
#define IDD_ALWAYS_BACK                 156
#define IDB_TAB_COLL_BITMAPD            160
#define IDD_ENTITY_EDIT                 161
#define IDD_COLL_EDIT                   162
#define IDD_ENTITY_FILE                 163
#define IDB_TAB_COLL_UP                 166
#define IDB_TAB_COLL_DN                 167
#define IDB_TAB_ENTITY_UP               170
#define IDB_TAB_ENTITY_DN               171
#define IDB_TAB_PARTICLE_DN             172
#define IDB_TAB_PARTICLE_UP             173
#define IDD_PARTICLE_FILE               174
#define IDD_PARTICLE_EDIT               175
#define IDD_PARTICLE_EDIT2              175
#define IDD_PARTICLE_PROPERTY           177
#define IDD_MAGIC_EDIT                  178
#define IDD_MAGIC_FILE                  179
#define IDD_SOUND_FILE                  180
#define IDD_SOUND_EDIT                  181
#define IDD_DUMMY_FILE                  183
#define IDD_DUMMY_EDIT                  184
#define IDD_DUMMY_DIALOG                185
#define IDB_TAB_MAGIC_DN                188
#define IDB_TAB_MAGIC_UP                189
#define IDB_TAB_SOUND_DN                190
#define IDB_TAB_SOUND_UP                191
#define IDB_TAB_DUMMY_DN                192
#define IDB_TAB_DUMMY_UP                193
#define IDD_DUMMY_SEARCH_DIALOG         195
#define IDD_DUMMY_SPLIT_DIALOG          196
#define IDD_DUMMY_ERROR_DIALOG          197
#define IDC_CHECK1                      1014
#define IDC_BUTTON1                     1015
#define IDC_CHECK13                     1015
#define IDC_BUTTON2                     1016
#define IDC_CHECK6                      1017
#define IDC_BUTTON7                     1017
#define IDC_CHECK3                      1018
#define IDC_BUTTON8                     1018
#define IDC_CHECK4                      1019
#define IDC_BUTTON9                     1019
#define IDC_RADIO1                      1020
#define IDC_CHECK8                      1020
#define IDC_RADIO2                      1021
#define IDC_CHECK9                      1021
#define IDC_COMBO1                      1022
#define IDC_CHECK25                     1022
#define IDC_RADIO3                      1023
#define IDC_CHECK27                     1023
#define IDC_COMBO3                      1023
#define IDC_CHECK5                      1024
#define IDC_CHECK7                      1025
#define IDC_CHECK10                     1026
#define IDC_BUTTON3                     1027
#define IDC_CHECK14                     1027
#define IDC_BUTTON4                     1028
#define IDC_CHECK15                     1028
#define IDC_BUTTON5                     1029
#define IDC_CHECK16                     1029
#define IDC_CHECK11                     1030
#define IDC_CHECK17                     1030
#define IDC_BUTTON10                    1030
#define IDC_CHECK2                      1031
#define IDC_CHECK12                     1031
#define IDC_BUTTON11                    1031
#define IDC_EDIT1                       1032
#define IDC_CHECK18                     1032
#define IDC_EDIT2                       1033
#define IDC_CHECK26                     1033
#define IDC_COMBO2                      1034
#define IDC_CHECK19                     1034
#define IDC_EDIT15                      1034
#define IDC_EDIT3                       1035
#define IDC_EDIT23                      1035
#define IDC_EDIT4                       1036
#define IDC_EDIT24                      1036
#define IDC_BUTTON12                    1036
#define IDC_CHECK28                     1036
#define IDC_EDIT5                       1037
#define IDC_EDIT6                       1038
#define IDC_CHECK20                     1038
#define IDC_CHECK21                     1039
#define IDC_EDIT18                      1039
#define IDC_CHECK22                     1040
#define IDC_EDIT19                      1040
#define IDC_CHECK23                     1041
#define IDC_EDIT20                      1041
#define IDC_CHECK24                     1042
#define IDC_EDIT25                      1043
#define IDC_EDIT21                      1044
#define IDC_CHECK29                     1044
#define IDC_BUTTON6                     1045
#define IDC_EDIT22                      1045
#define IDC_EDIT26                      1046
#define IDC_EDIT27                      1047
#define IDC_TAB1                        1052
#define IDC_SPIN1_PNUM                  1057
#define IDC_SPIN1_PNUM1                 1057
#define IDC_SPIN1_PNUM2                 1058
#define IDC_SPIN1_PNUM3                 1059
#define IDC_PROGRESS1                   1059
#define IDC_SPIN1_PNUM4                 1060
#define IDC_TAB_COLL_BUTTON             1060
#define IDC_SPIN1_PNUM5                 1061
#define IDC_TAB_ENTITY_BUTTON           1061
#define IDC_SPIN1_PNUM6                 1062
#define IDC_TAB_PARTICLE_BUTTON         1062
#define IDC_TAB_MAGIC_BUTTON            1063
#define IDC_EDIT7                       1064
#define IDC_TAB_SOUND_BUTTON            1064
#define IDC_EDIT8                       1065
#define IDC_TAB_DUMMY_BUTTON            1065
#define IDC_EDIT9                       1066
#define IDC_SLIDER1                     1067
#define IDC_EDIT_ATTACH_ENTITY          1068
#define IDC_BUTTON_ENTITY_LOAD          1069
#define IDC_EDIT10                      1070
#define IDC_EDIT11                      1071
#define IDC_EDIT12                      1072
#define IDC_EDIT13                      1073
#define IDC_EDIT14                      1074
#define IDC_TRACK_COLOR0                1076
#define IDC_EDIT_MAGIC_NAME             1076
#define IDC_TRACK_COLOR1                1077
#define IDC_EDIT_PARTICLE_NAME          1077
#define IDC_TRACK_COLOR2                1078
#define IDC_TRACK_COLOR3                1079
#define IDC_EDIT16                      1079
#define IDC_TRACK_COLOR4                1080
#define IDC_EDIT17                      1080
#define IDC_TRACK_COLOR5                1081
#define ID_FILE_MAP_ENTITY_LOAD         32773
#define ID_TAB_COLLSION                 32774
#define ID_TAB_ENTITY                   32775
#define ID_TAB_PARTICLE                 32776
#define ID_ENTER_KEY                    32777
#define ID_FILE_MAP_DUMMY_OPEN          32778
#define ID_FILE_OPEN_EBP                32779
#define ID_FILE_MAP_DUMMY_SAVE          32781
#define ID_FILE_DUMMY_OPEN              32782
#define ID_FILE_DUMMY_SAVE              32783
#define ID_FILE_SOUND_ENTITY_SAVE       32784
#define ID_FILE_SOUND_ENTITY_LOAD       32785
#define ID_FILE_SOUND_ENTITY_OPEN       32786
#define ID_FILE_MAP_ENTITY_ADD_OPEN     32787
#define EDIT_DISPLAY                    65535
#define ATT_DISPLAY                     65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        198
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
